package models

import "time"

// ArchitectSessionStatus represents the status of an architect session
type ArchitectSessionStatus string

const (
	ArchitectStatusActive    ArchitectSessionStatus = "active"
	ArchitectStatusCompleted ArchitectSessionStatus = "completed"
	ArchitectStatusAbandoned ArchitectSessionStatus = "abandoned"
)

// ArchitectPhase represents the current phase in the architect wizard
type ArchitectPhase string

const (
	PhaseVisionRefinement ArchitectPhase = "vision_refinement"
	PhaseArchitecture     ArchitectPhase = "architecture"
	PhaseRiskAnalysis     ArchitectPhase = "risk_analysis"
	PhasePhasing          ArchitectPhase = "phasing"
	PhaseDependencies     ArchitectPhase = "dependencies"
	PhaseEstimation       ArchitectPhase = "estimation"
	PhaseReview           ArchitectPhase = "review"
	PhaseComplete         ArchitectPhase = "complete"
)

// ArchitectTaskPhase represents which phase a generated task belongs to
type ArchitectTaskPhase string

const (
	TaskPhaseMVP        ArchitectTaskPhase = "mvp"
	TaskPhaseTwo        ArchitectTaskPhase = "phase_2"
	TaskPhaseThree      ArchitectTaskPhase = "phase_3"
	TaskPhaseMitigation ArchitectTaskPhase = "mitigation"
)

// ArchitectSession represents an architect planning session
type ArchitectSession struct {
	ID          string                 `json:"id"`
	ProjectID   string                 `json:"project_id"`
	Title       string                 `json:"title"`
	Description string                 `json:"description"`
	Status      ArchitectSessionStatus `json:"status"`
	Phase       ArchitectPhase         `json:"phase"`
	VisionData  string                 `json:"vision_data"`  // JSON: user answers from refinement
	ArchData    string                 `json:"arch_data"`    // JSON: architecture recommendations
	RiskData    string                 `json:"risk_data"`    // JSON: risk analysis results
	PhaseData   string                 `json:"phase_data"`   // JSON: MVP/phase breakdown
	DepData     string                 `json:"dep_data"`     // JSON: dependency graph
	EstData     string                 `json:"est_data"`     // JSON: resource estimates
	TemplateID  *string                `json:"template_id,omitempty"`
	CreatedAt   time.Time              `json:"created_at"`
	UpdatedAt   time.Time              `json:"updated_at"`
}

// ArchitectMessage represents a message in the multi-turn conversation
type ArchitectMessage struct {
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
	Role      string         `json:"role"` // "user" or "assistant"
	Content   string         `json:"content"`
	Phase     ArchitectPhase `json:"phase"`
	CreatedAt time.Time      `json:"created_at"`
}

// ArchitectTask represents a task generated by the architect session
type ArchitectTask struct {
	ID          string             `json:"id"`
	SessionID   string             `json:"session_id"`
	Title       string             `json:"title"`
	Prompt      string             `json:"prompt"`
	Phase       ArchitectTaskPhase `json:"phase"`
	Priority    int                `json:"priority"`
	DependsOn   string             `json:"depends_on"`   // JSON array of task IDs
	IsBlocking  bool               `json:"is_blocking"`
	Complexity  string             `json:"complexity"`    // low, medium, high
	EstHours    float64            `json:"est_hours"`
	TaskID      *string            `json:"task_id,omitempty"` // linked real task ID after activation
	IsActivated bool               `json:"is_activated"`
	CreatedAt   time.Time          `json:"created_at"`
}

// ArchitectTemplate represents a saved project blueprint
type ArchitectTemplate struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Category    string    `json:"category"` // e.g., "web_app", "api", "data_pipeline"
	VisionData  string    `json:"vision_data"`
	ArchData    string    `json:"arch_data"`
	TasksData   string    `json:"tasks_data"` // JSON array of template tasks
	UsageCount  int       `json:"usage_count"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// ArchitectDashboardData aggregates data for the architect page
type ArchitectDashboardData struct {
	ActiveSessions    []ArchitectSession  `json:"active_sessions"`
	CompletedSessions []ArchitectSession  `json:"completed_sessions"`
	Templates         []ArchitectTemplate `json:"templates"`
}

// ArchitectSessionDetail provides full session data for the wizard view
type ArchitectSessionDetail struct {
	Session  ArchitectSession  `json:"session"`
	Messages []ArchitectMessage `json:"messages"`
	Tasks    []ArchitectTask   `json:"tasks"`
}

// VisionRefinementData holds the parsed vision refinement answers
type VisionRefinementData struct {
	ProjectGoals    string   `json:"project_goals"`
	TargetUsers     string   `json:"target_users"`
	Constraints     string   `json:"constraints"`
	SuccessMetrics  string   `json:"success_metrics"`
	Timeline        string   `json:"timeline"`
	TechPreferences string   `json:"tech_preferences"`
	Differentiators string   `json:"differentiators"`
	Summary         string   `json:"summary"`
}

// ArchRecommendation holds architecture recommendations
type ArchRecommendation struct {
	TechStack      []ArchOption `json:"tech_stack"`
	Architecture   []ArchOption `json:"architecture"`
	Patterns       []ArchOption `json:"patterns"`
	Infrastructure []ArchOption `json:"infrastructure"`
	Summary        string       `json:"summary"`
}

// ArchOption represents a single architecture option with pros/cons
type ArchOption struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Pros        []string `json:"pros"`
	Cons        []string `json:"cons"`
	Recommended bool     `json:"recommended"`
}

// RiskAnalysis holds the risk analysis results
type RiskAnalysis struct {
	Risks   []ProjectRisk `json:"risks"`
	Summary string        `json:"summary"`
}

// ProjectRisk represents a single identified risk
type ProjectRisk struct {
	Category    string `json:"category"` // technical, scaling, security, timeline, resource
	Title       string `json:"title"`
	Description string `json:"description"`
	Severity    string `json:"severity"`   // low, medium, high, critical
	Likelihood  string `json:"likelihood"` // low, medium, high
	Mitigation  string `json:"mitigation"`
}

// PhaseBreakdown holds the MVP/phase planning data
type PhaseBreakdown struct {
	MVP    PhaseDetail `json:"mvp"`
	Phase2 PhaseDetail `json:"phase_2"`
	Phase3 PhaseDetail `json:"phase_3"`
}

// PhaseDetail describes a single phase
type PhaseDetail struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Features    []string `json:"features"`
	EstWeeks    int      `json:"est_weeks"`
}

// ResourceEstimate holds resource estimation data
type ResourceEstimate struct {
	TotalHours float64                  `json:"total_hours"`
	TotalTasks int                      `json:"total_tasks"`
	Complexity string                   `json:"complexity"` // simple, moderate, complex
	AIAPICost  string                   `json:"ai_api_cost"`
	Summary    string                   `json:"summary"`
	ByPhase    map[string]PhaseEstimate `json:"by_phase"`
}

// PhaseEstimate holds per-phase estimates
type PhaseEstimate struct {
	Tasks int     `json:"tasks"`
	Hours float64 `json:"hours"`
	Weeks int     `json:"weeks"`
}
