package pages

import (
	"fmt"
	templateui "github.com/openvibely/openvibely/web/templates"
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestBrowserFunctional_SharedTooltips(t *testing.T) {
	chrome := chatNavigationChromePath(t)
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `<!doctype html><html><meta charset="utf-8"><body style="--bc:.95 0 0;--ov-menu-surface:#252a33"><button id="native" title="Review changes (⌘⇧D)" aria-describedby="existing">Changes</button><span id="existing">Description</span><button id="state" title="Collapse sidebar (Ctrl+B)" data-tip="Running">State</button><dialog id="dialog"><button id="help" data-model-help="Helpful explanation">Help</button></dialog><canvas id="chart"></canvas>`)
		_ = templateui.Tooltips().Render(r.Context(), w)
		fmt.Fprint(w, `</body></html>`)
	}))
	defer server.Close()
	runComposerFocusCDP(t, chrome, server.URL, "shared-tooltips", func(b *composerFocusCDP) {
		b.waitFor("tooltip controller ready", `typeof window.openVibelyTooltip`, "object")
		b.evaluate(`var card=document.createElement('div');card.dataset.ovTooltip='Select tasks (Command+click)';card.innerHTML='<button data-kanban-menu-trigger aria-label="More actions"><svg><path/></svg></button>';document.body.appendChild(card);card.dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));'card'`)
		b.waitFor("card selection hint visible", `String(!document.getElementById('ov-shared-tooltip').hidden)`, "true")
		b.evaluate(`var kebab=card.querySelector('button'),icon=kebab.querySelector('path');card.dispatchEvent(new PointerEvent('pointerout',{bubbles:true,relatedTarget:icon}));icon.dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));'kebab'`)
		b.waitFor("kebab suppresses ancestor hint", `String(document.getElementById('ov-shared-tooltip').hidden)`, "true")
		b.evaluate(`kebab.focus();kebab.dispatchEvent(new FocusEvent('focusin',{bubbles:true}));'focus'`)
		b.waitFor("focused kebab has no inherited hint", `String(document.getElementById('ov-shared-tooltip').hidden && kebab.getAttribute('aria-label')==='More actions')`, "true")
		b.evaluate(`card.dispatchEvent(new PointerEvent('pointerover',{bubbles:true,relatedTarget:icon}));'return'`)
		b.waitFor("card hint returns outside kebab", `String(!document.getElementById('ov-shared-tooltip').hidden)`, "true")
		b.evaluate(`kebab.removeAttribute('data-kanban-menu-trigger');kebab.setAttribute('data-tooltip-disabled','');icon.dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));'disabled'`)
		b.waitFor("opted-out close button blocks inherited hint", `String(document.getElementById('ov-shared-tooltip').hidden)`, "true")
		b.evaluate(`kebab.removeAttribute('data-tooltip-disabled');kebab.classList.add('ov-modal-close');kebab.setAttribute('aria-label','Close dialog');kebab.title='Close dialog';icon.dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));kebab.dispatchEvent(new FocusEvent('focusin',{bubbles:true}));'modal-close'`)
		b.waitFor("modal close suppresses own and inherited hints", `String(document.getElementById('ov-shared-tooltip').hidden && kebab.getAttribute('aria-label')==='Close dialog')`, "true")
		b.evaluate(`card.remove();'removed'`)

		b.evaluate(`document.getElementById('native').focus();document.getElementById('native').dispatchEvent(new FocusEvent('focusin',{bubbles:true}));'ready'`)

		b.evaluate(`var control=document.getElementById('native');control.dispatchEvent(new PointerEvent('pointerover',{bubbles:true,clientX:320,clientY:220}));'hover'`)
		b.waitFor("tooltip follows pointer", `document.getElementById('ov-shared-tooltip').style.left`, "332px")
		b.evaluate(`document.body.dispatchEvent(new CustomEvent('htmx:beforeSwap',{bubbles:true,detail:{target:document.getElementById('chart')}}));document.getElementById('chart').dispatchEvent(new PointerEvent('pointerout',{bubbles:true}));window.hoverCheck=null;setTimeout(()=>window.hoverCheck=!document.getElementById('ov-shared-tooltip').hidden,300);'waiting'`)
		b.waitFor("unrelated events do not expire hovered tooltip", `String(window.hoverCheck)`, "true")
		b.evaluate(`control.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:420,clientY:220}));'move'`)
		b.waitFor("moving across wide control follows cursor", `document.getElementById('ov-shared-tooltip').style.left`, "432px")
		b.evaluate(`var cell=document.createElement('div');cell.title='Review changes (⌘⇧D)';document.body.appendChild(cell);control.dispatchEvent(new PointerEvent('pointerout',{bubbles:true,relatedTarget:cell}));cell.dispatchEvent(new PointerEvent('pointerover',{bubbles:true,relatedTarget:control,clientX:430,clientY:220}));'cell'`)
		b.waitFor("same hint transfers without hiding", `String(!document.getElementById('ov-shared-tooltip').hidden && cell.getAttribute('aria-describedby')==='ov-shared-tooltip')`, "true")
		b.evaluate(`control.dispatchEvent(new PointerEvent('pointerover',{bubbles:true,clientX:320,clientY:220}));'back'`)
		b.evaluate(`control.dispatchEvent(new MouseEvent('mousedown',{bubbles:true}));control.dispatchEvent(new FocusEvent('focusin',{bubbles:true}));control.dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));'pressed'`)
		b.waitFor("mousedown dismisses and focus cannot reopen", `String(document.getElementById('ov-shared-tooltip').hidden)`, "true")
		b.evaluate(`document.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));document.body.dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));control.dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));'reenter'`)
		b.evaluate(`control.dispatchEvent(new MouseEvent('mousedown',{bubbles:true}));cell.dispatchEvent(new PointerEvent('pointerover',{bubbles:true,buttons:1}));'drag'`)
		b.waitFor("drag across controls suppresses hints", `String(document.getElementById('ov-shared-tooltip').hidden)`, "true")
		b.evaluate(`document.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));var menu=document.createElement('div');menu.className='ov-menu';menu.setAttribute('role','menu');menu.textContent='Actions';document.body.appendChild(menu);cell.dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));'menu'`)
		b.waitFor("open popup suppresses other controls", `String(document.getElementById('ov-shared-tooltip').hidden)`, "true")
		b.evaluate(`menu.hidden=true;control.dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));'closed menu'`)
		b.waitFor("shortcut badge", `document.querySelector('#ov-shared-tooltip kbd').textContent`, "⌘⇧D")
		b.waitFor("native title suppressed", `String(!document.getElementById('native').hasAttribute('title'))`, "true")
		b.evaluate(`document.getElementById('native').title='Loading models';'updated'`)
		b.waitFor("dynamic title", `document.getElementById('ov-shared-tooltip').textContent`, "Loading models")
		b.evaluate(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));'closed'`)
		b.waitFor("description preserved", `document.getElementById('native').getAttribute('aria-describedby')`, "existing")
		b.waitFor("no native tooltip after Escape", `String(!document.getElementById('native').hasAttribute('title'))`, "true")
		b.evaluate(`var fresh=document.createElement('button');fresh.id='fresh';fresh.title='Review changes (Ctrl+Shift+D)';fresh.textContent='Review';document.body.appendChild(fresh);'inserted'`)
		b.waitFor("inserted tooltip adopted", `document.getElementById('fresh').dataset.ovTooltip`, "Review changes (Ctrl+Shift+D)")
		b.evaluate(`document.getElementById('fresh').dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));'hovered'`)
		b.waitFor("Windows shortcut badge", `document.querySelector('#ov-shared-tooltip kbd').textContent`, "Ctrl+Shift+D")
		b.evaluate(`document.body.style.setProperty('--ov-menu-surface','#ffffff');'theme'`)
		b.waitFor("theme follows menu surface", `getComputedStyle(document.getElementById('ov-shared-tooltip')).backgroundColor`, "rgb(255, 255, 255)")
		b.evaluate(`document.getElementById('fresh').remove();'removed'`)
		b.waitFor("removed owner dismisses tooltip", `String(document.getElementById('ov-shared-tooltip').hidden)`, "true")
		b.waitFor("latest label retained", `document.getElementById('native').dataset.ovTooltip`, "Loading models")
		b.evaluate(`document.getElementById('state').focus();document.getElementById('state').dispatchEvent(new FocusEvent('focusin',{bubbles:true}));'ready'`)
		b.waitFor("custom tooltip", `document.getElementById('ov-shared-tooltip').textContent`, "Running")
		b.evaluate(`document.getElementById('state').dataset.tip='Expand sidebar (Ctrl+B)';'updated'`)
		b.waitFor("sidebar state updates despite adopted title", `document.getElementById('ov-shared-tooltip').textContent`, "Expand sidebarCtrl+B")
		b.evaluate(`window.openVibelyTooltip.clear(document.getElementById('state'));'cleared'`)
		b.waitFor("clearing active tooltip dismisses it", `String(document.getElementById('ov-shared-tooltip').hidden)`, "true")
		b.evaluate(`document.getElementById('native').focus();document.getElementById('native').removeAttribute('title');document.getElementById('native').removeAttribute('data-ov-tooltip');'cleared'`)
		b.waitFor("breadcrumb removal dismisses adopted title", `String(document.getElementById('ov-shared-tooltip').hidden && !document.getElementById('native').hasAttribute('data-ov-tooltip'))`, "true")
		b.evaluate(`document.getElementById('native').dispatchEvent(new PointerEvent('pointerover',{bubbles:true}));'hovered'`)
		b.waitFor("removed tooltip stays absent on hover", `String(document.getElementById('ov-shared-tooltip').hidden)`, "true")

		b.evaluate(`document.getElementById('dialog').showModal();document.getElementById('help').focus();document.getElementById('help').dispatchEvent(new FocusEvent('focusin',{bubbles:true}));'ready'`)
		b.waitFor("modal tooltip", `String(document.getElementById('dialog').contains(document.getElementById('ov-shared-tooltip')) && document.getElementById('ov-shared-tooltip').matches(':popover-open'))`, "true")
		b.evaluate(`document.getElementById('dialog').close();window.openVibelyTooltip.chart({chart:{canvas:document.getElementById('chart')},tooltip:{opacity:1,title:['Tokens'],body:[{lines:['Model: 12']}],footer:['n=3'],caretX:5,caretY:5}});'chart'`)
		b.waitFor("chart callback text", `document.getElementById('ov-shared-tooltip').textContent`, "TokensModel: 12n=3")
		b.evaluate(`window.openVibelyTooltip.chart({chart:{canvas:document.getElementById('chart')},tooltip:{opacity:0}});'closed'`)
		b.waitFor("chart hidden", `String(document.getElementById('ov-shared-tooltip').hidden)`, "true")

		for _, modifier := range []string{"Command", "Ctrl"} {
			b.evaluate(`window.openVibelyTooltip.show(document.getElementById('native'),'Select schedules (` + modifier + `+click)\nMore actions (Rightclick)\nSelect or deselect a day (Click)\nSelect days across headers (Click and drag)');'shown'`)
			b.waitFor("schedule gestures follow labels", `String(Array.from(document.querySelectorAll('#ov-shared-tooltip .ov-tooltip-row')).every(row=>row.children.length===2 && row.firstElementChild.tagName==='SPAN' && row.lastElementChild.tagName==='KBD'))`, "true")
			b.waitFor("schedule modifier badge", `document.querySelector('#ov-shared-tooltip kbd').textContent`, modifier+"+click")
		}
		b.evaluate(`var wide=document.createElement('button');wide.title='Switch task (⌘K); Previous/next: ⌘⇧↑/↓; Last visited: ⌘⇧L';wide.style.cssText='position:fixed;left:100px;top:300px;width:500px;height:40px';wide.textContent='Wide control';document.body.appendChild(wide);'ready'`)
		b.call("Input.dispatchMouseEvent", map[string]any{"type": "mouseMoved", "x": 400, "y": 320}, nil)
		b.waitFor("native pointer placement", `document.getElementById('ov-shared-tooltip').style.left`, "412px")
		b.waitFor("shortcut rows have breathing room", `String((function(){var keys=document.querySelectorAll('#ov-shared-tooltip kbd');return keys.length===3 && keys[1].getBoundingClientRect().top-keys[0].getBoundingClientRect().bottom>=4})())`, "true")
		b.evaluate(`window.longHover=null;setTimeout(()=>window.longHover=!document.getElementById('ov-shared-tooltip').hidden,1200);'waiting'`)
		b.waitFor("stationary native hover remains visible", `String(window.longHover)`, "true")
		b.call("Input.dispatchMouseEvent", map[string]any{"type": "mouseMoved", "x": 500, "y": 320}, nil)
		b.waitFor("native mouse movement repositions hint", `document.getElementById('ov-shared-tooltip').style.left`, "512px")
	})
}
